apiVersion: v1
kind: Service
metadata:
  name: financial-service
  namespace: tkllm-darija
  labels:
    app.kubernetes.io/name: financial-service
    app.kubernetes.io/part-of: tkllm-darija
    app.kubernetes.io/component: worker
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: financial-service
  ports:
    - name: metrics
      port: 9091
      targetPort: 9091
      protocol: TCP