apiVersion: 1

datasources:
  - name: Prometheus
    uid: DS_PROMETHEUS
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: DS_TEMPO

  # Alertmanager (uncomment when alertmanager is running)
  # - name: Alertmanager
  #   uid: DS_ALERTMANAGER
  #   type: alertmanager
  #   access: proxy
  #   url: http://alertmanager:9093
  #   isDefault: false