apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tkllm-darija

resources:
  - infrastructure.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/component: vector-store
  app.kubernetes.io/name: weaviate